---
title: "Final Project: Exploring Factors Contributing to Positive Changes in Mental Health for Children Transitioning Into Adulthood"
subtitle: "Clustering Nearest Neighbor"
author: "Travis Jones III"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Data, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: show
    self_contained: yes
---
**final_project_rule_learning.Rmd**.

# Rule Learning
```{r Common, warning=F, message=F, include=F, child='final_project_common.Rmd'}
```

## Apriori Helper Functions and Libraries
```{r Header, warning=F, message=F}
library(arules)
library(arulesViz)

# translate the obscure descriptions into the descriptive descriptions
join_descriptions <- function(df, df_stat) {
  df_new <- df
  colname <- colnames(df_new)
  colname <- colname[!colname %in% "PositiveChange"]
  for(i in 1:length(colname)) {
    if(is.null(attributes(df_stat[[colname[i]]])$class) == F && attributes(df_stat[[colname[i]]])$class != "factor" && attributes(df_stat[[colname[i]]])$class[3] == "double") {
      if(is.null(attributes(df_stat[[colname[i]]])$labels) == F && length(attributes(df_stat[[colname[i]]])$labels) > 0) {
        vect_labels <- attributes(df_stat[[colname[i]]])$labels
        df_new[colname[i]] <- lapply(df_new[colname[i]], as.character)
        for(l in 1:length(vect_labels)) {
          df_new[colname[i]] <- replace(df_new[colname[i]], df_new[colname[i]] == vect_labels[l], trimws(names(vect_labels)[l]))
        }
      }
    }
  }
  return(df_new)
}

# translate the transactions with the obscure descriptions into the descriptive descriptions
tranasctions_join_descriptions <- function(trans) {
  subbed_trans <- trans
  vect_label <- attr(subbed_trans, "itemInfo")[["labels"]]
  for(i in 1:length(vect_label)) {
    attr(subbed_trans, "itemInfo")[["labels"]][i] <- paste0(string_replace_description(vect_label[i], reg = "\\w+\\="), "|u", i)
  }
  attr(subbed_trans, "itemInfo")[["variables"]] <- as.factor(unlist(lapply(attr(subbed_trans, "itemInfo")[["variables"]], fieldname_to_description)))
  attr(subbed_trans, "itemInfo")[["levels"]] <- unlist(lapply(attr(subbed_trans, "itemInfo")[["levels"]], string_replace_description, reg = "\\w+\\="))
  return(subbed_trans)
}

# replace an apriori string / description with the descriptive fieldnames (not the obscure fieldnames)
string_replace_description <- function(sub, reg) {
  vect_strings <- unlist(str_split(sub, "="))
  new_reg <- str_replace(reg, "\\\\=", "$")
  for(i in 1:length(vect_strings)) {
    extracted <- str_extract(vect_strings[i], new_reg)
    if(!is.na(extracted) && length(extracted) > 0)
      vect_strings[i] <- str_replace(vect_strings[i], extracted, fieldname_to_description(extracted))
  }
  # str_extract(sub, reg)
  # extracted <- gsub("[[:punct:]]+", "", extracted)
  # sub <- str_replace(sub, extracted, fieldname_to_description(extracted))
  return(paste(vect_strings, collapse="="))
}
```

## Apriori Learning - Full Dataset
```{r AprioriFull, warning=F, message=F}
num_rules_full <- 45
df_full_apriori <- join_descriptions(df_full_na, tbl_dta)
transactions_full <- transactions(df_full_apriori)
# summary(transactions_full)
# inspect(transactions_full[1:2,])
transactions_full_subbed <- tranasctions_join_descriptions(transactions_full)
#itemFrequency(transactions_full_subbed[,1:5])

##for rules
myrules_full <- apriori(transactions_full_subbed, parameter = list(support = 0.25))
myrules_full_sorted <- sort(myrules_full, by="lift")
myrules_full_sorted
# summary(myrules_full)
inspect(head(myrules_full_sorted, n = num_rules_full))
plot(myrules_full_sorted, method = "graph", engine = "htmlwidget", control = list(main = list(title="Rules for the Full Dataset")), max = num_rules_full)
# Runs out of Memory
#plot(myrules_full, method = "grouped matrix", k = 7, rhs_max = 5, engine = "htmlwidget")
```

## Apriori Learning - Objective Dataset
```{r AprioriObjective, warning=F, message=F}
num_rules_objective <- 45
df_objective_apriori <- join_descriptions(df_objective_na, tbl_dta)
transactions_objective <- transactions(df_objective_apriori)
# summary(transactions_objective)
# inspect(transactions_objective[1:2,])
transactions_objective_subbed <- tranasctions_join_descriptions(transactions_objective)
#itemFrequency(transactions_objective_subbed[,1:5])

myrules_objective <- apriori(transactions_objective_subbed, parameter = list(support = 0.25))
myrules_objective_sorted <- sort(myrules_objective, by="lift")
myrules_objective_sorted
# summary(myrules_objective_sorted)
inspect(head(sort(myrules_objective_sorted, by="lift"), n = num_rules_objective))
plot(sort(myrules_objective_sorted, by="lift"), method = "graph", engine = "htmlwidget", control = list(main = list(title="Rules for the Objective Dataset")), max = num_rules_objective)
# Runs out of Memory
# plot(myrules_objective, method = "grouped matrix", k = 7, rhs_max = 7, engine = "htmlwidget")
```

## Summary

Based upon both the full and objective dataset, it appears the feature relationships that had the biggest impact on PositiveChange are below.
```{r Summary, warning=F, message=F}
intersect(inspect(head(myrules_full_sorted, n = num_rules_objective)), inspect(head(myrules_objective_sorted, n = num_rules_objective)))
```
